owner: Liminova
repo: status

sites:
  - name: organization website
    url: https://liminova.net
  - name: charlotte synapse
    url: $CHARLOTTE_SYNAPSE
  - name: charlotte api
    url: $CHARLOTTE_API

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: liminova status
  cname: status.liminova.net
  introTitle: "Status page for various things under the Liminova organization."
  introMessage: Powered by [upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://liminova.net
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
