owner: Liminova
repo: status

sites:
  - name: organization website
    url: https://liminova.github.io

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: uptime status
  introTitle: "Status page for various things under the Liminova organization."
  introMessage: Powered by [upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /status
    - title: Homepage
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
