# Change these first
owner: Liminova # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: organization website
    url: https://liminova.github.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: uptime status
  introTitle: "Status page for various things under the Liminova organization."
  introMessage: Powered by [upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /status
    - title: Homepage
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
